# Generated by Django 4.0.5 on 2022-08-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='pro',
        ),
    ]
