# Generated by Django 4.0.5 on 2022-08-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0003_rename_product_cartitem_pro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='pro',
            new_name='product',
        ),
    ]
